### PR TITLE
Suggested build-and-run script for development.

### PR DESCRIPTION
**Pull request by mottosso**
Starting of gently, I'm curious as to how you typically try Feather whilst developing.

Here's what I have been doing, do you have a different/recommended method?

### CODE REVIEW

**Comment by mottosso** [comment]
Also, might as well get to the bottom of this; on a clean build, I'm getting a few errors I solved bruteforce, but maybe we could have a look at getting this to build cleanly?

```
marcus@ubuntu:~/feather$ cd build
marcus@ubuntu:~/feather$ cmake ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Boost version: 1.54.0
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   filesystem
--   system
CMake Error at src/lib/qml/shaders/CMakeLists.txt:2 (add_subdirectory):
  The source directory

    /home/marcus/feather/src/lib/qml/shaders/geom

  does not contain a CMakeLists.txt file.
```

Here's what I've had to do.

```bash
$ cp -r src/lib/qml/shaders/vert/* src/lib/qml/shaders/geom/
$ nano nano assets/images/CMakeLists.txt
# Comment out the last line
```

**Comment by richardlayman** [comment]
You don't have Doxygen installed or it's installed in a location that cmake can't find which shouldn't be the case. Also, your boost is a few versions off mine - you have 1.54 and I have 1.59 but that shouldn't really make a difference. I just did a commit https://github.com/feather3d/feather/commit/b98bd65b2dc6321e07f8b5f0b052143f8eeedf41 that fixes this issue by not building doxygen - which you shouldn't have to do except when building the api docs. Other then that, I'm getting no errors from this my end. I wiped everything clean and rebuilt with no errors, warnings, everything went to their proper place and the application ran fine, so I'm not sure where these issues are coming from.

This is how I build

    $ cd feather/build
    $ cmake ..
    $ sudo make install

The only thing that snags up is I have to 

    $ sudo ldconfig /usr/lib/feather/

But that's only when I update my Arch. This will all change when I start making packages - at that time I'll start running from a sandbox in user space and make a package if I want to run it from the system space. And packages remove the need for ldconfig. Also, there are many times that I just want to run cmake or make by themselves to test certain things. Lately I've been mostly running coretest instead of the ui since it's faster to test the sg with.

**Comment by mottosso** [comment]
I installed Arch and tried building but got a slightly different error. :(

```
[root@eb105440ad8e build]# uname -a
Linux eb105440ad8e 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 GNU/Linux
[root@e53520f97779 build]# cmake ..
-- The C compiler identification is GNU 5.2.0
-- The CXX compiler identification is GNU 5.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenGL: /usr/lib64/libGL.so
-- Boost version: 1.59.0
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   filesystem
--   system
CMake Error at src/lib/qml/shaders/CMakeLists.txt:2 (add_subdirectory):
  add_subdirectory given source "geom" which is not an existing directory.

```

**Comment by mottosso** [comment]
> This is how I build

Sounds good; discarding the build script, keeping it simple is better.

**Comment by richardlayman** [comment]
I just pushed a fix for this - 
https://github.com/feather3d/feather/commit/75654d19eb659561fdf070495352dd902d17ff9a
The reason you got this error was because I was working with geometry shaders but then found out that my version of mesa does not support them yet so I had to remove them but forgot to disable them CMake.

Also, one other thing to point out, it's always a good idea to rebuild the plugins after you build the core or some weird things could happen.

**Comment by mottosso** [comment]
> Also, one other thing to point out, it's always a good idea to rebuild the plugins after you build the core or some weird things could happen.

Ah! Have not been doing that, will keep that in mind.

**Comment by mottosso** [comment]
> I just pushed a fix for this - 

About this, what do you think about never pushing to this repo; but instead only producing pull-requests from forks? In this case, you'd fork feather to your personal account, and submit a pull-request.

The reason being that (1) it's difficult to know when things change and what change and (2) pull-requests are good for code review and finally (3) it would allow the master repo to always be in a buildable and runnable state. No PR's would get accepted without first being buildable and passing the tests.

Will be setting up Travis for this soon.

**Comment by richardlayman** [comment]
If it's in the master branch it's should always build and work fine unless a statement has been added to the commit explaining the problem.

>About this, what do you think about never pushing to this repo; but instead only producing pull-requests from forks? In this case, you'd fork feather to your personal account, and submit a pull-request.

Yea, I should've been do that a while ago.

**Comment by mottosso** [comment]
> Yea, I should've been do that a while ago.

Let's do it! I'll start considering pushes to this repo as a mistake from now on.

**Comment by mottosso** [comment]
Could you approve the request for Travis-CI? Have you gotten any?

**Comment by richardlayman** [comment]
I'm still want to do some research on this, didn't have the time yesterday. I'll look into it tonight.

**Comment by mottosso** [comment]
Sure, take your time.

**Comment by richardlayman** [comment]
I'm adding the v0.1 branch to feather, feather-ui, and feather-plugins so we can push for development but still have a stable master branch. We'll merge v0.1 into master once we feel it's 'stable'.

**Comment by mottosso** [comment]
That's the opposite of a fork-and-pull-request workflow though. If we stick to pull-requests, we won't need branches, other than in our personal repos. I'd really recommend this, I've had nothing but great experiences with this kind of workflow so far.

**Comment by richardlayman** [comment]
We are still forking and using our forks, we just do our pull request to the v0.1 branch.

**Comment by mottosso** [comment]
But we don't need it. We can pull-request directly into Master, and only do so when we know it works.

If I need code from you, before merging to master, I'll just pull directly from your account; and vice versa.

If we need to tag a particular commit as v0.1 or v1.0, we'll use releases.

**Comment by richardlayman** [comment]
Yes, we will tag our release but there also needs to be a development branch for that release as well.
example:
https://github.com/qtproject/qt-creator

**Comment by mottosso** [comment]
I wouldn't compare our workflow to something as large as Qt. We are much smaller, and require a smaller workflow.

I dunno, I have plentiful of experience with my suggested workflow and am sure it will cover our use case, but you possibly have a lot of experience with this in which case I'm fine with either. I leave it to you.

**Comment by richardlayman** [comment]
Yes, currently we don't need this. But as the project grows is could get very large and I would like to have a branch history of all the versions and just for good habit.

**Comment by mottosso** [comment]
> Also, one other thing to point out, it's always a good idea to rebuild the plugins after you build the core or some weird things could happen.

About this, is the idea for plug-ins to remain as-is inbetween releases of Feather? Or will plug-ins need recompilation for each release?

**Comment by richardlayman** [comment]
The plugins only depend on the core, as long as the core's interface doesn't change the plugins don't need to be recompiled. Which is why I would like to get the core ironed out as much as possible for v0.1.

When I can the core 'interface' I mean it's functions calls. The functions code can change as much as possible and it won't effect the plugins at all. But if a function is changed from something like

    void get_node(int uid, int& nid);

to

    void get_node(std::string name, int& nid);

That will cause problems and the plugins would need to be recompiled. Being the core is constantly changing at this point, it's safe to assume that the plugins will need to recompiled if you see any changes to src/lib/core/* in your merge.

**Comment by mottosso** [comment]
Ah, that's perfect!

**Pull request closed without merging**
